export const SET_ALL_SUBJECTS = 'SET_ALL_SUBJECTS';
export const SET_SELECTED_SUBJECT = 'SET_SELECTED_SUBJECT';

export const REMOVE_ALL_SUBJECTS = 'REMOVE_ALL_SUBJECTS';
export const REMOVE_SELECTED_SUBJECT = 'REMOVE_SELECTED_SUBJECT';