export const SET_ALL_COURSES = 'SET_ALL_COURSES';
export const SET_SELECTED_COURSE = 'SET_SELECTED_COURSE';

export const REMOVE_ALL_COURSES = 'REMOVE_ALL_COURSES';
export const REMOVE_SELECTED_COURSE = 'REMOVE_SELECTED_COURSE';