export const SET_ALL_CHAPTERS = 'SET_ALL_CHAPTERS';
export const SET_SELECTED_CHAPTER = 'SET_SELECTED_CHAPTER';

export const REMOVE_ALL_CHAPTERS = 'REMOVE_ALL_CHAPTERS';
export const REMOVE_SELECTED_CHAPTER = 'REMOVE_SELECTED_CHAPTER';